version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - REACT_APP_API_URL=http://192.168.192.5:4000
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - TMDB_API_KEY=${TMDB_API_KEY}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: keinos/sqlite3:latest
    volumes:
      - ./data:/data
    command: ["tail", "-f", "/dev/null"]
    restart: unless-stopped

volumes:
  frontend_node_modules:
  backend_node_modules:

networks:
  default:
    driver: bridge
